# Generated by Django 4.2 on 2025-12-01 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModelDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, null=True, verbose_name='字典大类')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='字典大类的名字')),
                ('key', models.CharField(max_length=64, null=True, unique=True, verbose_name='字典属性的索引键')),
                ('value', models.CharField(max_length=64, null=True, verbose_name='字典属性的值')),
                ('label', models.CharField(max_length=64, null=True, verbose_name='字典属性的显示名称')),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
                'db_table': 'system_datamodel_dict',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='设置项的键')),
                ('value', models.CharField(max_length=64, null=True, verbose_name='设置项的值')),
                ('description', models.TextField(null=True, verbose_name='设置项的描述')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='SysMenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
                ('path', models.CharField(max_length=64, verbose_name='前端路径')),
                ('component', models.CharField(max_length=64, null=True, verbose_name='组件路径')),
                ('permission', models.CharField(max_length=64, null=True, verbose_name='可访问权限')),
                ('icon', models.CharField(max_length=16, null=True, verbose_name='图标')),
                ('title', models.CharField(max_length=64, verbose_name='显示标题')),
                ('isHide', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('isKeepAlive', models.BooleanField(default=True, verbose_name='是否缓存')),
                ('isAffix', models.BooleanField(default=False, verbose_name='是否固定')),
                ('isFull', models.BooleanField(default=False, verbose_name='是否全屏')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sysmenusettings', verbose_name='父级')),
            ],
            options={
                'verbose_name': '系统菜单设置',
                'verbose_name_plural': '系统菜单设置',
                'db_table': 'system_menu_settings',
            },
        ),
    ]
