# Generated by Django 4.2 on 2025-12-01 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDreamovingCosTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('image_url', models.CharField(max_length=1024, verbose_name='图片地址')),
                ('tags', models.CharField(max_length=1024, null=True, verbose_name='模板类型标签，多个用逗号分隔')),
                ('popularity', models.IntegerField(default=108, verbose_name='热度')),
                ('description', models.TextField(null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '追影API模板',
                'verbose_name_plural': '追影API模板',
                'db_table': 'lgtools_cvdreamoving_cos_templates',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HeaderPosterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('image_url', models.CharField(max_length=1024, verbose_name='图片地址')),
                ('description', models.TextField(null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '首页海报配置',
                'db_table': 'digishow_headerposter_config',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.IntegerField(null=True, verbose_name='权限')),
                ('description', models.CharField(max_length=128, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '功能权限的定义基础表',
                'verbose_name_plural': '功能权限的定义基础表',
                'db_table': 'system_privilege',
            },
        ),
        migrations.CreateModel(
            name='ProductTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('type', models.IntegerField(choices=[(1, 'Cartoon Show'), (2, 'Dressing On'), (3, 'Word Art')], verbose_name='类型')),
                ('image_url', models.CharField(max_length=1024, verbose_name='图片地址')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('description', models.TextField(null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '产品模板配置',
                'db_table': 'digishow_product_template',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='评测题目文字')),
                ('options', models.TextField(verbose_name='评测题目的选项')),
                ('quest_class', models.IntegerField(null=True, verbose_name='本题属于哪一型')),
                ('quest_type', models.IntegerField(default=1, verbose_name='题型：1-青少年版；2-副型测试')),
            ],
            options={
                'verbose_name': '评测题目',
                'verbose_name_plural': '评测题目',
                'db_table': 'ninetype_question',
            },
        ),
        migrations.CreateModel(
            name='ToolsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.CharField(max_length=1024, null=True, verbose_name='描述')),
                ('cover', models.CharField(max_length=1024, null=True, verbose_name='封面图片的地址')),
                ('path', models.CharField(max_length=1024, null=True, verbose_name='工具的地址')),
                ('popularity', models.IntegerField(default=108, verbose_name='热度')),
                ('available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('price', models.IntegerField(default=0, verbose_name='使用一次消耗的点数')),
                ('order', models.IntegerField(default=999, verbose_name='排序')),
            ],
            options={
                'verbose_name': '工具配置',
                'verbose_name_plural': '工具配置',
                'db_table': 'lgtools_config',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserManageAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, null=True, verbose_name='验证用的token')),
                ('wx_openid', models.CharField(max_length=128, null=True, verbose_name='微信openid')),
                ('wx_unionid', models.CharField(max_length=128, null=True, verbose_name='微信unionid')),
                ('nickname', models.CharField(max_length=128, null=True, verbose_name='微信的昵称')),
                ('headimgurl', models.CharField(max_length=256, null=True, verbose_name='微信头像')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='手机号')),
                ('channel', models.IntegerField(choices=[(1, 'Tranditional'), (2, 'Sms'), (3, 'Wechat Mini Program'), (4, 'Wechat H5')], default=1, verbose_name='用户渠道')),
                ('credential', models.TextField(null=True, verbose_name='用户凭证相关的原始数据，json格式存储')),
                ('infomation', models.TextField(null=True, verbose_name='用户不重要的基本资料都放里面（性别、省市等），json格式存储')),
                ('balance', models.IntegerField(default=0, verbose_name='积分余额')),
                ('level', models.IntegerField(default=1, verbose_name='用户等级')),
                ('register_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='最后登录时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '管理用户账户',
                'db_table': 'system_user_manage_account',
            },
        ),
        migrations.CreateModel(
            name='UserTradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('order_no', models.CharField(max_length=128, null=True, verbose_name='订单号，系统内创建的，有的交易有，有的没有')),
                ('trade_type', models.IntegerField(choices=[(1, '充值'), (2, '消费')], default=1, verbose_name='交易类型')),
                ('amount', models.IntegerField(default=0, verbose_name='交易积分')),
                ('trade_time', models.DateTimeField(auto_now_add=True, verbose_name='交易发生时间')),
                ('remark', models.CharField(max_length=256, null=True, verbose_name='备注说明')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '交易明细',
                'verbose_name_plural': '交易明细',
                'db_table': 'system_user_trade_record',
                'ordering': ['-trade_time'],
            },
        ),
        migrations.CreateModel(
            name='UserToolsPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('privilege', models.IntegerField(default=0, verbose_name='权限开通情况')),
                ('open_time', models.DateTimeField(null=True, verbose_name='开通时间')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.toolsconfig', verbose_name='工具')),
            ],
            options={
                'verbose_name': '用户工具权限',
                'verbose_name_plural': '用户工具权限',
                'db_table': 'lgtools_user_tools_privilege',
            },
        ),
        migrations.CreateModel(
            name='UserReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('finished', models.BooleanField(default=False, verbose_name='是否完成评测')),
                ('report_flag', models.IntegerField(default=0, verbose_name='报告生成的状态标识')),
                ('report', models.TextField(null=True, verbose_name='解读报告')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户报告记录',
                'verbose_name_plural': '用户报告记录',
                'db_table': 'ninetype_report_record',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='用户姓名')),
                ('school_class', models.CharField(max_length=32, null=True, verbose_name='班级')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户账户',
                'verbose_name_plural': '用户账户',
                'db_table': 'ninetype_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('order_no', models.CharField(max_length=128, unique=True, verbose_name='订单号，系统内创建的')),
                ('trade_no', models.CharField(max_length=128, null=True, verbose_name='交易号，第三方支付返回的')),
                ('provider', models.CharField(default='weixin', max_length=128, verbose_name='支付渠道方')),
                ('order_desc', models.CharField(max_length=256, null=True, verbose_name='订单描述')),
                ('amount', models.IntegerField(null=True, verbose_name='订单金额，单位分')),
                ('payer', models.CharField(max_length=128, null=True, verbose_name='付款人信息')),
                ('status', models.IntegerField(choices=[(0, '等待支付'), (1, '已支付'), (2, '已取消')], default=0, verbose_name='订单状态')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户订单',
                'verbose_name_plural': '用户订单',
                'db_table': 'system_user_order',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_time', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('feedback_content', models.TextField(verbose_name='反馈内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'db_table': 'system_user_feedback',
            },
        ),
        migrations.CreateModel(
            name='UserEvaluationAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('answer_option', models.TextField(verbose_name='用户选择的选项')),
                ('answer_score', models.IntegerField(default=0, verbose_name='用户选择的选项对应的分数(从题目设置表中冗余出来方便计算)')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='superadmin.question', verbose_name='评测题目')),
            ],
            options={
                'verbose_name': '用户评测答案',
                'verbose_name_plural': '用户评测答案',
                'db_table': 'ninetype_evaluation_answers',
            },
        ),
        migrations.CreateModel(
            name='UserDigitalFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('image_url', models.CharField(max_length=1024, verbose_name='图片地址，可能存在多个')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '数字形象',
                'verbose_name_plural': '数字形象',
                'db_table': 'digishow_digital_figure',
            },
        ),
        migrations.CreateModel(
            name='UserDigiProducingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('desc', models.CharField(max_length=32, null=True, verbose_name='记录描述')),
                ('task_id', models.CharField(max_length=32, verbose_name='任务ID')),
                ('type', models.IntegerField(choices=[(1, 'Cartoon Show'), (2, 'Dressing On'), (3, 'Word Art')], verbose_name='制作模板的类型')),
                ('image_url', models.CharField(max_length=1024, null=True, verbose_name='图片地址')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='制作完成时间')),
                ('cost', models.IntegerField(default=0, verbose_name='消耗积分')),
                ('status', models.IntegerField(default=0, verbose_name='任务生成状态：0-生成中，1-生成成功，2-生成失败')),
                ('task_detail', models.CharField(max_length=1024, null=True, verbose_name='任务失败时的详情描述')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '制作记录',
                'verbose_name_plural': '制作记录',
                'db_table': 'digishow_producing_record',
            },
        ),
        migrations.CreateModel(
            name='UserAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.CharField(max_length=128, null=True, verbose_name='用户代理')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户访问日志',
                'verbose_name_plural': '用户访问日志',
                'db_table': 'system_user_access_log',
            },
        ),
        migrations.CreateModel(
            name='ToolsProducingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('task_id', models.CharField(max_length=32, verbose_name='任务ID')),
                ('type', models.IntegerField(choices=[(1, 'Cvdreamoving'), (2, 'Aiposter'), (3, 'Wordart'), (4, 'Photorecover')], verbose_name='制作工具的类型')),
                ('product', models.CharField(max_length=1024, null=True, verbose_name='作品结果地址')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='制作完成时间')),
                ('cost', models.IntegerField(null=True, verbose_name='消耗积分')),
                ('status', models.IntegerField(default=0, verbose_name='任务生成状态：0-生成中，1-生成成功，2-生成失败')),
                ('task_detail', models.CharField(max_length=1024, null=True, verbose_name='任务失败时的详情描述')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '制作记录',
                'verbose_name_plural': '制作记录',
                'db_table': 'lgtools_producing_record',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='OrignalImageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('tool', models.CharField(max_length=32, verbose_name='工具名称')),
                ('image_url', models.CharField(max_length=1024, verbose_name='图片地址')),
                ('upload_time', models.DateTimeField(verbose_name='上传时间')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '原始图片记录',
                'verbose_name_plural': '原始图片记录',
                'db_table': 'lgtools_orignal_image_record',
            },
        ),
        migrations.CreateModel(
            name='ComposeTaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('subject', models.TextField(max_length=32, verbose_name='写作主题')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('outline', models.TextField(verbose_name='文章大纲')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('step', models.IntegerField(blank=True, choices=[(1, '主题'), (2, '大纲'), (3, '标题'), (4, '文章')], null=True, verbose_name='当前步骤')),
                ('status', models.IntegerField(choices=[(0, '编写中'), (1, '编写完成')], default=0, verbose_name='任务状态')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '写作任务详情',
                'verbose_name_plural': '写作任务详情',
                'db_table': 'articalagent_compose_task_detail',
            },
        ),
    ]
