# Generated by Django 4.2 on 2025-12-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composetaskdetail',
            old_name='subject',
            new_name='topic',
        ),
    ]
