# Generated by Django 4.2 on 2026-01-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_rename_subject_composetaskdetail_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('urgency_grade', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=1, verbose_name='紧急程度')),
                ('content', models.TextField(verbose_name='待办/日程事项的详细内容')),
                ('categories', models.CharField(max_length=128, verbose_name='分类标签,用逗号分隔')),
                ('fire_time', models.DateTimeField(verbose_name='触发时间')),
                ('status', models.IntegerField(choices=[(0, '待办'), (1, '已完成'), (2, '已取消')], default=0, verbose_name='状态')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.usermanageaccount', verbose_name='所属用户')),
            ],
            options={
                'ordering': ['-create_time'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='composetaskdetail',
            name='owner',
        ),
        migrations.DeleteModel(
            name='CVDreamovingCosTemplates',
        ),
        migrations.DeleteModel(
            name='HeaderPosterConfig',
        ),
        migrations.RemoveField(
            model_name='orignalimagerecord',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ProductTemplateConfig',
        ),
        migrations.RemoveField(
            model_name='toolsproducingrecord',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userdigiproducingrecord',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userdigitalfigure',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userevaluationanswers',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userevaluationanswers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userreportrecord',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='usertoolsprivilege',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='usertoolsprivilege',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='usertraderecord',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ComposeTaskDetail',
        ),
        migrations.DeleteModel(
            name='OrignalImageRecord',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='ToolsConfig',
        ),
        migrations.DeleteModel(
            name='ToolsProducingRecord',
        ),
        migrations.DeleteModel(
            name='UserDigiProducingRecord',
        ),
        migrations.DeleteModel(
            name='UserDigitalFigure',
        ),
        migrations.DeleteModel(
            name='UserEvaluationAnswers',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserReportRecord',
        ),
        migrations.DeleteModel(
            name='UserToolsPrivilege',
        ),
        migrations.DeleteModel(
            name='UserTradeRecord',
        ),
    ]
